### ISSUE TITLE
Reference Provider has trouble with certain string variables

### ISSUE THREAD

**Issue by NoDataFound** [infosec-intern/vscode-yara#17]
Reference Provider  looks like it has trouble with certain string variable lengths.

Example:

`strings:
      $x1 = "Error = Process.Create(\"powershell -nop cmd.exe /c" fullword ascii`

"x1" will not engage the reference provider and display any references.

![referencest](https://raw.githubusercontent.com/infosec-intern/textmate-yara/master/images/references.PNG)

**Comment by infosec-intern** [comment]
Thanks, looking into this

**Comment by infosec-intern** [comment]
@NoDataFound do you have the YARA rule you were using handy so I can verify the fix?

**Comment by NoDataFound** [comment]
https://github.com/Yara-Rules/rules/blob/master/Crypto/crypto_signatures.yar should replicate the issue.

**Comment by infosec-intern** [comment]
@NoDataFound published 1.2.1 in response. Let me know if you still have the same problem

Closing issue. Feel free to reopen

**Comment by NoDataFound** [comment]
Works perfectly. Thank you for the quick turnaround.
