### ISSUE TITLE
Please remove "rule" snippet

### ISSUE THREAD

**Issue by tlansec** [infosec-intern/vscode-yara#19]
Hey,

I love the YARA syntax highlighting library you provide and thanks for coding it!

In more recent versions you have added a snippet for a rule like this:

{
	"Rule": {
		"prefix": "rule",
		"body": [
			"/*",
			"\tRULE DESCRIPTION HERE",
			"*/",
			"rule ${name}",
			"{",
			"\tcondition:",
			"\t\t$1",
			"}"
		],
		"description": "Generate a basic skeleton"
	},
	"Meta": {
		"prefix": "meta",
		"body": [
			"meta:",
			"\t${metadata}"
		],
		"description": "Generate a 'meta' section"
	},
	"Strings": {
		"prefix": "strings",
		"body": [
			"strings:",
			"\t${string(s)}"
		],
		"description": "Generate a 'strings' section"
	},
	"Import": {
		"prefix": "import",
		"body": "import \"${module}\"",
		"description": "Import a YARA module"
	}
}

Whenever VSCode updates, this overrides the default snippet I had created myself for rules which prepopulates metadata sections etc.

Would you consider removing the rule snippet, and instead leave it to users to define their own snippets?

Cheers,
Tom

**Comment by infosec-intern** [comment]
Glad you like it, and thanks for the feedback! 

I'm hesitant to completely remove that snippet in case others use it and find it useful. However, I'll do some digging and see if there's a way to not override user-defined snippets when I publish an update. 

Also, if you have any custom changes that are shareable with the wider community, feel free to make a PR or suggest a change. I'm more than happy to improve that area of the extension; it's been a while since I've touched them.

**Comment by tlansec** [comment]
Unfortunately I think there isn't a way to override or disable snippets defined in extensions: https://github.com/Microsoft/vscode/issues/10565

I currently use a snippet like this, unsure if this is preferable the current shorter default snippet. 

{
    "Rule": {
        "prefix": "rule",
        "body": [
            "rule ${1} : ",
            "{",
            "    meta:",
            "        author = \"$MYNAME""
            "        date = \"\""
            "        description = \"\""
            "        hash = \"\""
            ""
            "    strings:"
            "        $ = \"\""
            ""
            "    condition:",
            "        ",
            "}"
        ],
        "description": "Generate a basic skeleton"
    }
}

Obviously its up to you and i will certainly continue to use your extension regardless of whether you make any changes to the snippets.

**Comment by infosec-intern** [comment]
Do you have a User Snippet and a YARA snippet available in your menu or are you overriding the built-in snippets?

Thanks for the issue link; i didn't realize this was such a wide-ranging issue across extensions. The best solution in the short term might be to add a YARA Snippets extension to support both people who want them provided and those who want to create personal ones

**Comment by infosec-intern** [comment]
Just pushed out [a new release](https://github.com/infosec-intern/vscode-yara/releases/tag/v1.5.0) that re-works the snippets and adds configuration settings to enable/disable the section and rule snippets. I hope this is a good compromise and still fits your needs with the extension.

Closing this issue, but please feel free to reopen or create a new issue if you have any additional feedback. Thank you!
