### ISSUE TITLE
Hex string highlights invalid non-hex characters

### ISSUE THREAD

**Issue by wesinator** [infosec-intern/vscode-yara#26]
Current basic hex string regex highlights any characters between `= { }`

<img width="254" alt="image" src="https://user-images.githubusercontent.com/5124946/59159442-9c63ed00-8a97-11e9-8181-ea3e74300e57.png">

**Expected:** only highlight valid hex string chars `a-fA-F0-9?`
This will help with identifying invalid strings in rules

**Comment by infosec-intern** [comment]
@wesinator ... and 2 years later I believe this has been fixed. I'll be adding this to release 1.6.0 after I attempt to apply the same logic to address issue #28. In the meantime, if you get around to it can you take a look at the screenshot in the linked PR and let me know if that is or is not what you're looking for, please?
