### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by DanielRuf** [infosec-intern/vscode-yara#31]
I think the repo name can be updated.

**Comment by wesinator** [comment]
there is a new version of this project at https://github.com/infosec-intern/vscode-yara

**Comment by infosec-intern** [comment]
@DanielRuf to clarify on the above (and sorry for the long delay), wesinator is right in that https://github.com/infosec-intern/vscode-yara is the newer version of this project, but this repository is still the one that the YARA extension is being built from today. The way this one works limits me to certain features in a way that vscode-yara is not limited to, but I'm still working on thoroughly testing the newer project and ensuring installation is as smooth as possible. This repository still gets periodic updates to fix bugs and to comply with newer YARA syntaxes (e.g. the 4.0 release this year), but at some point when it's ready I will start building the YARA extension from the vscode-yara repository.

If you have any questions/comments/concerns, please feel free to file an issue or PR. There's also now a minimal GitHub Pages site at https://infosec-intern.github.io/vscode-yara/ with more information about the newer version of the project.
