### ISSUE TITLE
private rules do not support goto definition, peek definition, ctrl+click

### ISSUE THREAD

**Issue by manshantsingh** [infosec-intern/vscode-yara#32]
Goto definition, peek definition, ctrl+click etc do not work with private rules.

Example below: ctrl+click on the condition ```my_private_rule``` will not take you to the definition of ```my_private_rule```

```
private rule my_private_rule
{
    condition:
        true
}

rule my_public_rule
{
    condition:
        my_private_rule
}
```

**Comment by infosec-intern** [comment]
Thanks for filing an issue! I just pushed out a new version to address this. Closing this issue for now, but please feel free to reopen if I didn't fully address your use case.
